### ISSUE TITLE
Errors in Frontend

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#69]
In fronend, the plugin is causing error in JS Console.

	Uncaught TypeError: a.indexOf is not a function
		at r.fn.init.r.fn.load (jquery.min.js:4)
		at HTMLDocument.<anonymous> (inventor.js?ver=20161208:235)
		at j (jquery.min.js:2)
		at k (jquery.min.js:2)
	r.fn.load @ jquery.min.js:4
	(anonymous) @ inventor.js?ver=20161208:235
	j @ jquery.min.js:2
	k @ jquery.min.js:2
	jquery.min.js:4 Uncaught TypeError: a.indexOf is not a function
		at r.fn.init.r.fn.load (jquery.min.js:4)
		at HTMLDocument.<anonymous> (script.js:3)
		at j (jquery.min.js:2)
		at k (jquery.min.js:2)

**Comment by shubhiD** [comment]
May be an issue with jQuery version currently being loaded

**Comment by rohitmanglik** [comment]
We should work with the default jQuery version provided over there else our version of jQuery will cause compatibility issues with other plugins.

**Comment by shubhiD** [comment]
check this, is this the error?
http://stackoverflow.com/questions/38871753/uncaught-typeerror-a-indexof-is-not-a-function-error-when-opening-new-foundat

**Comment by vSharique** [comment]
I'll check it out

**Comment by vSharique** [comment]
I'll check it out

On Feb 4, 2017 12:19 AM, "Anantharam Venkatesan" <notifications@github.com>
wrote:

Assigned #69 <https://github.com/EduGorilla/lead-marketplace/issues/69> to
@vSharique <https://github.com/vSharique>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EduGorilla/lead-marketplace/issues/69#event-948522369>,
or mute the thread

**Comment by anantharam** [comment]
Resolved by changing jQuery version.
